FROM golang:1.22-alpine AS builder

COPY . /github.com/mchekalov/auth/service/source
WORKDIR /github.com/mchekalov/auth/service/source

RUN go mod download
RUN go build -o ./bin/crud_server cmd/server/main.go

FROM alpine:latest

WORKDIR /root/
COPY --from=builder /github.com/mchekalov/auth/service/source/bin/crud_server .

CMD ["./crud_server"]